/**
 * user-service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1-20180911-442
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CreateUserModel {
    aliasMailAddress?: string;
    businessMailAddress?: string;
    cognitoId?: string;
    companyId?: string;
    firstname?: string;
    lastname?: string;
    phone?: string;
    position?: string;
}
